# Generated by Django 5.0.1 on 2024-01-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameraheartbeat',
            name='hw_platform',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cameraheartbeat',
            name='time_zone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cameraheartbeat',
            name='version',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
