# Generated by Django 4.2.7 on 2023-11-19 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0004_account_tent_delete_customuser_account_assigned_tent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tent',
            name='air_condition',
        ),
        migrations.RemoveField(
            model_name='tent',
            name='air_condition_update_time',
        ),
        migrations.RemoveField(
            model_name='tent',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='tent',
            name='tent_id',
        ),
        migrations.AlterField(
            model_name='tent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tent',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tent',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tent',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tent',
            name='long',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
