# Generated by Django 4.2.7 on 2023-12-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_camera'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='new_field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
