# Generated by Django 4.2.7 on 2023-12-08 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_counterhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=255)),
                ('version', models.IntegerField()),
                ('ip_address', models.CharField(max_length=255)),
                ('time_zone', models.IntegerField()),
                ('hw_platform', models.CharField(max_length=255)),
                ('report_date', models.DateField()),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.camera')),
            ],
        ),
    ]
