# Generated by Django 4.2.7 on 2023-12-10 20:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_cameraheartbeat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cameraheartbeat',
            name='report_date',
        ),
        migrations.AddField(
            model_name='cameraheartbeat',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='cameraheartbeat',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
