# Generated by Django 4.2.7 on 2023-12-15 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_alter_cameraheartbeat_camera_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='status',
            field=models.BooleanField(default=False, help_text='Indicates if the camera is active or not'),
        ),
    ]
