# Generated by Django 4.2.7 on 2023-12-16 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_image_remove_picture_image_picture_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='picture',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='image_set', to='main_app.picture'),
        ),
    ]
